### ISSUE TITLE
Feedback 1° Sprint

### ISSUE THREAD

**Issue by nerdale** [nahytar/scl-2018-05-bc-core-am#1]
Mayra,

Bien desarrollado el HTML, excelente indentación  y orden :+1: 
El archivo **style.css** debes corregir la indentación que tienes de 4 espacios a 2 espacios.
En el archivo **index.js** debes revisar lo mismo con los espacios de indentación recién mencionados.

Lo demás está súper, salvo que no descifra, falta que arregles el método decode del objeto

**Comment by nahytar** [comment]
Arreglos hechos, gracias.
